### ISSUE TITLE
Attr.class does not allow whitespaces in class names

### ISSUE THREAD

**Issue by mlemerre** [janestreet/virtual_dom#8]
Hi,

Attr.class is defined as:

```
let class_ classname =
  if not (valid_class_name classname)
  then raise_s [%message "invalid classname" (classname : string)];
  Class (Set.singleton (module String) classname)
```
This is problematic because I would like to use Bulma elements, that define classes with whitespaces in it.

Is there a specific reason why not to allow whitespaces in class names? It seems to be valid HTML.

Best regards
Matthieu

**Comment by TyOverby** [comment]
Class names can not contain spaces.  You are probably thinking about the html syntax for adding multiple classes, separated by a space.  For this, we have 

```ocaml
val Vdom.Attr.classes : string list -> Vdom.Attr.t
```
